# Generated by Django 5.0.6 on 2024-10-15 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripton', models.TextField()),
                ('type', models.CharField(choices=[('single', 'SINGLE'), ('variant', 'VARIANT')], default='single', max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
            ],
        ),
    ]
