# Generated by Django 5.0.6 on 2024-10-16 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0004_vendor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleproductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='singleproductimages')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorapp.product')),
            ],
            options={
                'db_table': 'single_product_images',
            },
        ),
    ]
