# Generated by Django 5.0.6 on 2024-10-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0008_alter_singleproductimages_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripton',
            new_name='description',
        ),
    ]
