# Generated by Django 5.0.6 on 2024-10-17 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0009_rename_descripton_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('attribute', models.CharField(max_length=20)),
                ('is_variant', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='vendorapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='VariantProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='variantproductimages')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='vendorapp.productvariant')),
            ],
            options={
                'db_table': 'variant_product_images',
            },
        ),
    ]
