# Generated by Django 5.0.6 on 2024-10-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0012_remove_productvariant_is_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ImageField(null=True, upload_to='productimages'),
        ),
    ]
