# Generated by Django 5.0.6 on 2024-10-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0013_product_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_images',
            new_name='product_image',
        ),
    ]
