# Generated by Django 5.0.6 on 2024-10-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('vendorapp', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.CharField(max_length=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendorapp.product')),
            ],
        ),
    ]
