# Generated by Django 5.0.6 on 2024-10-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_banner_banner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_name',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
