# Generated by Django 5.0.6 on 2024-10-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
