# Generated by Django 5.0.6 on 2024-10-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_delete_adminuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerproducts',
            old_name='banner_id',
            new_name='banner',
        ),
    ]
